
// Generated by https://javiercbk.github.io/json_to_dart/
class Movie {
  String name;
  String photo;
  String author;
  int year;
  int status;

  Movie({this.name, this.photo, this.author, this.year, this.status});

  Movie.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    photo = json['photo'];
    author = json['author'];
    year = json['year'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['photo'] = this.photo;
    data['author'] = this.author;
    data['year'] = this.year;
    data['status'] = this.status;
    return data;
  }
}
